#! /bin/bash

PWD=`pwd`
DEST_PATH=zoos
KERN_OUT=kernel/arch/arm/boot
#帮助信息
usage(){
	echo "*******************************************************"
	echo -e "  $0 [target]"
	echo -e " "
	echo -e "\ttarget : uboot/kernel/all/eclipse \t default uboot"
	echo -e " "
	echo "*******************************************************"
}

#检查参数个数是否正确
if [ $# -ne 1 ] ; then
	usage
	exit 1
fi


#测试uboot是否编译成功
if [ "$1" == "uboot" ]; then
	if [ ! -e "$DEST_PATH/u-boot" ]; then
		echo "ERROR: please run \"./zoo uboot\" first"
	else
		#dd if=/dev/zero of=$DEST_PATH/flash0.img bs=1M count=64
		#dd if=$DEST_PATH/u-boot.bin of=$DEST_PATH/flash0.img bs=256k conv=notrunc
		#dd if=/dev/zero of=$DEST_PATH/flash1.img bs=1M count=64	
		#qemu-system-arm -M vexpress-a9 -m 256M -nographic -kernel $DEST_PATH/u-boot -net nic,vlan=0 -net tap,vlan=0,ifname=tap0
		qemu-system-arm -M vexpress-a9 -m 256M -nographic -kernel $DEST_PATH/u-boot -pflash $DEST_PATH/flash0.img -pflash $DEST_PATH/flash1.img -net nic,vlan=0 -net tap,vlan=0,ifname=tap0 -sd $DEST_PATH/rootfs.ext2
	fi
elif [ "$1" == "kernel" ]; then
	if [ ! -e "$DEST_PATH/zImage" ]; then
		echo "ERROR: please run \"./zoo kernel\" first"
	else	#单独验证内核通过-append传递参数，uboot中通过bootargs传递参数
		#qemu-system-arm -M vexpress-a9 -m 512M -kernel $DEST_PATH/zImage -nographic -append "root=/dev/mmcblk0 console=ttyAMA0" -sd $DEST_PATH/rootfs.ext2
		#qemu-system-arm -M vexpress-a9 -m 512M -kernel $DEST_PATH/zImage -nographic -append "root=/dev/mmcblk0 console=ttyAMA0"
		qemu-system-arm -M vexpress-a9 -m 512M -kernel $DEST_PATH/zImage -dtb $DEST_PATH/vexpress-v2p-ca9.dtb -nographic -append "root=/dev/mmcblk0 console=ttyAMA0 rw init=/linuxrc"
	fi
elif [ "$1" == "all" ]; then
	if [ ! -e "$DEST_PATH/u-boot" ]; then
		echo "ERROR: please run \"./zoo uboot\" first"
	elif [ ! -e "$DEST_PATH/zImage" ]; then
		echo "ERROR: please run \"./zoo kernel\" first"
	elif  [ ! -e "$DEST_PATH/rootfs.ext2" ]; then
		echo "ERROR: please run \"./zoo rootfs\" first"
	else
		qemu-system-arm -M vexpress-a9 -m 512M -kernel $DEST_PATH/u-boot -nographic -append "root=/dev/mmcblk0  console=ttyS0" -sd $DEST_PATH/rootfs.ext2
		#qemu-system-arm -M vexpress-a9 -m 256M -nographic -kernel $DEST_PATH/u-boot -net nic,vlan=0 -net tap,vlan=0,ifname=tap0 -sd $DEST_PATH/rootfs.ext2
	fi
elif [ "$1" == "eclipse" ]; then
	if [ ! -e "$DEST_PATH/zImage" ]; then
		echo "ERROR: please run \"./zoo kernel\" first"
	else
		#qemu-system-arm -M vexpress-a9 -m 256M -nographic -kernel arch/arm/boot/zImage -append "rdinit=/linuxrc console=ttyAMA0" -dtb arch/arm/boot/dts/vexpress-v2p-ca9.dtb  -gdb tcp::1236 -S
		qemu-system-arm -M vexpress-a9 -m 256M -nographic -kernel $KERN_OUT/zImage -append "rdinit=/linuxrc console=ttyAMA0" -dtb $KERN_OUT/dts/vexpress-v2p-ca9.dtb -S -s
	fi	
fi

#单独测试busybox
#qemu-system-arm -M vexpress-a9 -m 512M -kernel $DEST_PATH/zImage -nographic -append "root=/dev/mmcblk0  console=ttyAMA0" -sd a9rootfs.ext3
#flashimg -s 60M -t nand -f nand.bin -p mypart -w boot,u-boot.bin -z 512